name: update-ercot-hourly-load
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python install -r requirements.txt
      - name: execute script
        run: |
          cd ./data_prep
          python ercot_hourly_load.py
