name: ERCOT
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: execute script
        run: |
          cd ./scripts/data_prep
          python ercot_hourly_load.py
      - name: commit updated data
        run: |
          mv ./scripts/data_prep/tmp_data/combined.csv ./data/ercot_hourly_load.csv
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add ./data
          if [[ ! -z  $(git status -uno --porcelain) ]]; then git commit -m "updated ercot"; fi
          git push
