name: Weather
on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.ADMIN_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: execute script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          cd ./scripts/data_prep
          python weather.py
      - name: commit updated data
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add ./data
          if [[ ! -z  $(git status -uno --porcelain) ]]; then git commit -m "updated weather"; fi
          git push
