name: COVID-19
on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.ADMIN_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: execute script
        run: |
          cd ./scripts/data_prep
          python covid.py
      - name: commit updated data
        run: |
          mv ./scripts/data_prep/tmp_data/texas_covid_confirmed.csv ./data/texas_covid_confirmed.csv
          mv ./scripts/data_prep/tmp_data/texas_covid_deaths.csv ./data/texas_covid_deaths.csv
          git config user.name tailaiw
          git config user.email 29800495+tailaiw@users.noreply.github.com
          git pull
          git add ./data
          if [[ ! -z  $(git status -uno --porcelain) ]]; then git commit -m "updated covid"; fi
          git push
